baseURL = "http://example.org/"
languageCode = "en-us"
title = "Max Abbe"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]



[menu]
    [[menu.main]]
  	name="Home"
  	url="/"
	weight=1

   [[menu.main]]
  	name="Test"
  	url="/about/"
	weight=2
