baseURL = "http://example.org/"
languageCode = "en-us"
title = "Max Abbe"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]